### ISSUE TITLE
Calendar GUI in Landsat Search on EODN website not functioning

### ISSUE THREAD

**Issue by disprosium8** [datalogistics/dlt-web#1]
_From @batzli on September 9, 2015 19:28_

The calendars for the Landsat Search interface seem to not allow date selection either anymore (they used to work).  Only the "today" button populates the date field now.  I'm using Chrome on Win 7.

_Copied from original issue: datalogistics/ibp_server#15_

**Comment by disprosium8** [comment]
_From @PerilousApricot on September 9, 2015 19:29_

@batzli Hey, the web interface isn't a part of the depot software itself, so perhaps this isn't the best place to open these tickets. @disprosium8 -- do you have a better repo out there?

**Comment by disprosium8** [comment]
_From @batzli on September 9, 2015 19:32_

oops, sorry.  I don't know.  There must be a better place for website issues... I'm open to suggestions.  Ezra?

**Comment by disprosium8** [comment]
_From @PerilousApricot on September 9, 2015 19:32_

Perhaps https://github.com/datalogistics/dlt-web ?

**Comment by disprosium8** [comment]
Yes, these should all be in the dlt-web repo.  I'll see if I can move 
the issues.

**Comment by disprosium8** [comment]
_From @batzli on September 9, 2015 19:35_

sorry and thanks!

**Comment by prak5190** [comment]
Currently fixed in prod , Dates should now be allowed till the current date
