### ISSUE TITLE
exnodes not showing up in "Landsat Search" results

### ISSUE THREAD

**Issue by disprosium8** [datalogistics/dlt-web#2]
_From @batzli on September 9, 2015 19:26_

Confusing results between the Exnode Browser and the Landsat Search.  I can see Exnodes listed in the browser (such as Landsat/LC8/024/030/2015/LC80240302015180LGN00.jpg) but they don't show up in the Landsat Search.  All results are listed as at USGS only and no Exnode versions are found.

_Copied from original issue: datalogistics/ibp_server#14_

**Comment by prak5190** [comment]
Seems to work in dev , updated prod - Now the exnodes show up in prod
